title: "TestPedioa"
description: "Test de site avec des .md et Jekyll"
theme: minima

# Pour que GitHub Pages ne désactive pas Jekyll
markdown: kramdown

# Liens affichés dans l’en-tête
header_pages:
  - index.md
  - COPYING.md


collections:
  test:
    output: true                
    permalink: /test/:name      

