title: "Ma documentation"
description: "Exemple de site GitHub Pages avec Jekyll"
theme: minima

# Pour que GitHub Pages ne désactive pas Jekyll
markdown: kramdown

# (Optionnel) Liens de navigation dans l’en-tête du thème "minima"
header_pages:
  - index.md
  - COPYING.md
